### ISSUE TITLE
labels 

### ISSUE THREAD

**Issue by Abhinav-vats** [chamanthmvs/Phishing-Website-Detection#1]
what are labels in the csv file?

**Comment by subashvoleti32** [comment]
Can you please share a video on this project to get detailed information about this project.

**Comment by chamanthmvs** [comment]
@subashvoleti32 Sharing a video is not possible. You can clone it and try it out, if interested. 
Thanks

**Comment by chamanthmvs** [comment]
> what are labels in the csv file?

**Comment by chamanthmvs** [comment]
@Abhinav-vats (Please clearly understand the project and given files). It is a binary classification problem (Where you need to predict given url is legitimate or phishing). The data included in the project contains two types of csv files ( legitimate and phishing). Which are class labels. You will understand this, when you read any ipython notebook included in this repository. 

@subashvoleti32 Sorry, sharing a video for the same is not possible. You can try it out by cloning the project.
