### ISSUE TITLE
Why the legitimate link/site is labelled as phishing site?

### ISSUE THREAD

**Issue by raishaloy** [chamanthmvs/Phishing-Website-Detection#5]
Hi, I was trying a few links from legitimate-urls.csv and most of the links are labelled as phishing site and not legitimate site. Any solution to this? Thank you very much for your kind support

<img width="626" alt="screenshot2" src="https://user-images.githubusercontent.com/76470658/102985022-7272fe00-4549-11eb-9bcd-16a8373d30f5.png">

**Comment by chamanthmvs** [comment]
No data is present. It is a good example of false positive
